# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KeyboarddpagZi.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1263, 382)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        # self.pushButton.setGeometry(QRect(0, 0, 60, 60))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        # self.pushButton_2.setGeometry(QRect(0, 60, 60, 60))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        # self.pushButton_3.setGeometry(QRect(60, 60, 60, 60))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        # self.pushButton_4.setGeometry(QRect(240, 60, 60, 60))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        # self.pushButton_5.setGeometry(QRect(120, 60, 60, 60))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        # self.pushButton_6.setGeometry(QRect(180, 60, 60, 60))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        # self.pushButton_7.setGeometry(QRect(300, 60, 60, 60))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(360, 60, 60, 60))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(420, 60, 60, 60))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(480, 60, 60, 60))
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(540, 60, 60, 60))
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(600, 60, 60, 60))
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(660, 60, 60, 60))
        self.pushButton_14 = QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(720, 60, 60, 60))
        self.pushButton_15 = QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(780, 60, 120, 60))
        self.pushButton_16 = QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(0, 120, 91, 60))
        self.pushButton_17 = QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(90, 120, 60, 60))
        self.pushButton_18 = QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(150, 120, 60, 60))
        self.pushButton_19 = QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(210, 120, 60, 60))
        self.pushButton_20 = QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(270, 120, 60, 60))
        self.pushButton_21 = QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(330, 120, 60, 60))
        self.pushButton_22 = QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(390, 120, 60, 60))
        self.pushButton_23 = QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(450, 120, 60, 60))
        self.pushButton_24 = QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(510, 120, 60, 60))
        self.pushButton_25 = QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(570, 120, 60, 60))
        self.pushButton_26 = QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(630, 120, 60, 60))
        self.pushButton_27 = QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(690, 120, 60, 60))
        self.pushButton_28 = QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(750, 120, 60, 60))
        self.pushButton_29 = QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(120, 0, 60, 60))
        self.pushButton_30 = QPushButton(self.centralwidget)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(180, 0, 60, 60))
        self.pushButton_31 = QPushButton(self.centralwidget)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(240, 0, 60, 60))
        self.pushButton_32 = QPushButton(self.centralwidget)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(300, 0, 60, 60))
        self.pushButton_33 = QPushButton(self.centralwidget)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(390, 0, 60, 60))
        self.pushButton_34 = QPushButton(self.centralwidget)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(450, 0, 60, 60))
        self.pushButton_35 = QPushButton(self.centralwidget)
        self.pushButton_35.setObjectName(u"pushButton_35")
        self.pushButton_35.setGeometry(QRect(510, 0, 60, 60))
        self.pushButton_36 = QPushButton(self.centralwidget)
        self.pushButton_36.setObjectName(u"pushButton_36")
        self.pushButton_36.setGeometry(QRect(570, 0, 60, 60))
        self.pushButton_38 = QPushButton(self.centralwidget)
        self.pushButton_38.setObjectName(u"pushButton_38")
        self.pushButton_38.setGeometry(QRect(660, 0, 60, 60))
        self.pushButton_39 = QPushButton(self.centralwidget)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(720, 0, 60, 60))
        self.pushButton_40 = QPushButton(self.centralwidget)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.pushButton_40.setGeometry(QRect(780, 0, 60, 60))
        self.pushButton_41 = QPushButton(self.centralwidget)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.pushButton_41.setGeometry(QRect(840, 0, 60, 60))
        self.pushButton_37 = QPushButton(self.centralwidget)
        self.pushButton_37.setObjectName(u"pushButton_37")
        self.pushButton_37.setGeometry(QRect(900, 60, 60, 60))
        self.pushButton_42 = QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.pushButton_42.setGeometry(QRect(960, 60, 60, 60))
        self.pushButton_43 = QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.pushButton_43.setGeometry(QRect(960, 120, 60, 60))
        self.pushButton_44 = QPushButton(self.centralwidget)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.pushButton_44.setGeometry(QRect(900, 120, 60, 60))
        self.pushButton_45 = QPushButton(self.centralwidget)
        self.pushButton_45.setObjectName(u"pushButton_45")
        self.pushButton_45.setGeometry(QRect(960, 180, 60, 60))
        self.pushButton_46 = QPushButton(self.centralwidget)
        self.pushButton_46.setObjectName(u"pushButton_46")
        self.pushButton_46.setGeometry(QRect(900, 180, 60, 60))
        self.pushButton_47 = QPushButton(self.centralwidget)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.pushButton_47.setGeometry(QRect(900, 240, 60, 60))
        self.pushButton_48 = QPushButton(self.centralwidget)
        self.pushButton_48.setObjectName(u"pushButton_48")
        self.pushButton_48.setGeometry(QRect(900, 300, 60, 60))
        self.pushButton_49 = QPushButton(self.centralwidget)
        self.pushButton_49.setObjectName(u"pushButton_49")
        self.pushButton_49.setGeometry(QRect(960, 300, 60, 60))
        self.pushButton_50 = QPushButton(self.centralwidget)
        self.pushButton_50.setObjectName(u"pushButton_50")
        self.pushButton_50.setGeometry(QRect(840, 300, 60, 60))
        self.pushButton_51 = QPushButton(self.centralwidget)
        self.pushButton_51.setObjectName(u"pushButton_51")
        self.pushButton_51.setGeometry(QRect(1080, 60, 60, 60))
        self.pushButton_52 = QPushButton(self.centralwidget)
        self.pushButton_52.setObjectName(u"pushButton_52")
        self.pushButton_52.setGeometry(QRect(1020, 60, 60, 60))
        self.pushButton_53 = QPushButton(self.centralwidget)
        self.pushButton_53.setObjectName(u"pushButton_53")
        self.pushButton_53.setGeometry(QRect(1140, 60, 60, 60))
        self.pushButton_54 = QPushButton(self.centralwidget)
        self.pushButton_54.setObjectName(u"pushButton_54")
        self.pushButton_54.setGeometry(QRect(1200, 60, 60, 60))
        self.pushButton_55 = QPushButton(self.centralwidget)
        self.pushButton_55.setObjectName(u"pushButton_55")
        self.pushButton_55.setGeometry(QRect(1020, 120, 60, 60))
        self.pushButton_56 = QPushButton(self.centralwidget)
        self.pushButton_56.setObjectName(u"pushButton_56")
        self.pushButton_56.setGeometry(QRect(1080, 120, 60, 60))
        self.pushButton_57 = QPushButton(self.centralwidget)
        self.pushButton_57.setObjectName(u"pushButton_57")
        self.pushButton_57.setGeometry(QRect(1140, 120, 60, 60))
        self.pushButton_58 = QPushButton(self.centralwidget)
        self.pushButton_58.setObjectName(u"pushButton_58")
        self.pushButton_58.setGeometry(QRect(1140, 180, 60, 60))
        self.pushButton_59 = QPushButton(self.centralwidget)
        self.pushButton_59.setObjectName(u"pushButton_59")
        self.pushButton_59.setGeometry(QRect(1080, 180, 60, 60))
        self.pushButton_60 = QPushButton(self.centralwidget)
        self.pushButton_60.setObjectName(u"pushButton_60")
        self.pushButton_60.setGeometry(QRect(1020, 180, 60, 60))
        self.pushButton_61 = QPushButton(self.centralwidget)
        self.pushButton_61.setObjectName(u"pushButton_61")
        self.pushButton_61.setGeometry(QRect(1140, 240, 60, 60))
        self.pushButton_62 = QPushButton(self.centralwidget)
        self.pushButton_62.setObjectName(u"pushButton_62")
        self.pushButton_62.setGeometry(QRect(1080, 240, 60, 60))
        self.pushButton_63 = QPushButton(self.centralwidget)
        self.pushButton_63.setObjectName(u"pushButton_63")
        self.pushButton_63.setGeometry(QRect(1020, 240, 60, 60))
        self.pushButton_64 = QPushButton(self.centralwidget)
        self.pushButton_64.setObjectName(u"pushButton_64")
        self.pushButton_64.setGeometry(QRect(1140, 300, 60, 60))
        self.pushButton_65 = QPushButton(self.centralwidget)
        self.pushButton_65.setObjectName(u"pushButton_65")
        self.pushButton_65.setGeometry(QRect(1200, 240, 60, 120))
        self.pushButton_66 = QPushButton(self.centralwidget)
        self.pushButton_66.setObjectName(u"pushButton_66")
        self.pushButton_66.setGeometry(QRect(1200, 120, 60, 120))
        self.pushButton_67 = QPushButton(self.centralwidget)
        self.pushButton_67.setObjectName(u"pushButton_67")
        self.pushButton_67.setGeometry(QRect(1020, 300, 120, 60))
        self.pushButton_68 = QPushButton(self.centralwidget)
        self.pushButton_68.setObjectName(u"pushButton_68")
        self.pushButton_68.setGeometry(QRect(1140, 0, 60, 60))
        self.pushButton_69 = QPushButton(self.centralwidget)
        self.pushButton_69.setObjectName(u"pushButton_69")
        self.pushButton_69.setGeometry(QRect(1200, 0, 60, 60))
        self.pushButton_70 = QPushButton(self.centralwidget)
        self.pushButton_70.setObjectName(u"pushButton_70")
        self.pushButton_70.setGeometry(QRect(0, 180, 101, 60))
        self.pushButton_71 = QPushButton(self.centralwidget)
        self.pushButton_71.setObjectName(u"pushButton_71")
        self.pushButton_71.setGeometry(QRect(0, 240, 131, 60))
        self.pushButton_72 = QPushButton(self.centralwidget)
        self.pushButton_72.setObjectName(u"pushButton_72")
        self.pushButton_72.setGeometry(QRect(0, 300, 91, 60))
        self.pushButton_74 = QPushButton(self.centralwidget)
        self.pushButton_74.setObjectName(u"pushButton_74")
        self.pushButton_74.setGeometry(QRect(100, 180, 60, 60))
        self.pushButton_75 = QPushButton(self.centralwidget)
        self.pushButton_75.setObjectName(u"pushButton_75")
        self.pushButton_75.setGeometry(QRect(160, 180, 60, 60))
        self.pushButton_76 = QPushButton(self.centralwidget)
        self.pushButton_76.setObjectName(u"pushButton_76")
        self.pushButton_76.setGeometry(QRect(220, 180, 60, 60))
        self.pushButton_77 = QPushButton(self.centralwidget)
        self.pushButton_77.setObjectName(u"pushButton_77")
        self.pushButton_77.setGeometry(QRect(280, 180, 60, 60))
        self.pushButton_78 = QPushButton(self.centralwidget)
        self.pushButton_78.setObjectName(u"pushButton_78")
        self.pushButton_78.setGeometry(QRect(340, 180, 60, 60))
        self.pushButton_79 = QPushButton(self.centralwidget)
        self.pushButton_79.setObjectName(u"pushButton_79")
        self.pushButton_79.setGeometry(QRect(400, 180, 60, 60))
        self.pushButton_80 = QPushButton(self.centralwidget)
        self.pushButton_80.setObjectName(u"pushButton_80")
        self.pushButton_80.setGeometry(QRect(460, 180, 60, 60))
        self.pushButton_81 = QPushButton(self.centralwidget)
        self.pushButton_81.setObjectName(u"pushButton_81")
        self.pushButton_81.setGeometry(QRect(520, 180, 60, 60))
        self.pushButton_82 = QPushButton(self.centralwidget)
        self.pushButton_82.setObjectName(u"pushButton_82")
        self.pushButton_82.setGeometry(QRect(580, 180, 60, 60))
        self.pushButton_83 = QPushButton(self.centralwidget)
        self.pushButton_83.setObjectName(u"pushButton_83")
        self.pushButton_83.setGeometry(QRect(640, 180, 60, 60))
        self.pushButton_84 = QPushButton(self.centralwidget)
        self.pushButton_84.setObjectName(u"pushButton_84")
        self.pushButton_84.setGeometry(QRect(700, 180, 60, 60))
        self.pushButton_85 = QPushButton(self.centralwidget)
        self.pushButton_85.setObjectName(u"pushButton_85")
        self.pushButton_85.setGeometry(QRect(760, 180, 60, 60))
        self.pushButton_86 = QPushButton(self.centralwidget)
        self.pushButton_86.setObjectName(u"pushButton_86")
        self.pushButton_86.setGeometry(QRect(130, 240, 60, 60))
        self.pushButton_87 = QPushButton(self.centralwidget)
        self.pushButton_87.setObjectName(u"pushButton_87")
        self.pushButton_87.setGeometry(QRect(190, 240, 60, 60))
        self.pushButton_88 = QPushButton(self.centralwidget)
        self.pushButton_88.setObjectName(u"pushButton_88")
        self.pushButton_88.setGeometry(QRect(250, 240, 60, 60))
        self.pushButton_89 = QPushButton(self.centralwidget)
        self.pushButton_89.setObjectName(u"pushButton_89")
        self.pushButton_89.setGeometry(QRect(310, 240, 60, 60))
        self.pushButton_90 = QPushButton(self.centralwidget)
        self.pushButton_90.setObjectName(u"pushButton_90")
        self.pushButton_90.setGeometry(QRect(370, 240, 60, 60))
        self.pushButton_91 = QPushButton(self.centralwidget)
        self.pushButton_91.setObjectName(u"pushButton_91")
        self.pushButton_91.setGeometry(QRect(430, 240, 60, 60))
        self.pushButton_92 = QPushButton(self.centralwidget)
        self.pushButton_92.setObjectName(u"pushButton_92")
        self.pushButton_92.setGeometry(QRect(490, 240, 60, 60))
        self.pushButton_93 = QPushButton(self.centralwidget)
        self.pushButton_93.setObjectName(u"pushButton_93")
        self.pushButton_93.setGeometry(QRect(550, 240, 60, 60))
        self.pushButton_94 = QPushButton(self.centralwidget)
        self.pushButton_94.setObjectName(u"pushButton_94")
        self.pushButton_94.setGeometry(QRect(610, 240, 60, 60))
        self.pushButton_95 = QPushButton(self.centralwidget)
        self.pushButton_95.setObjectName(u"pushButton_95")
        self.pushButton_95.setGeometry(QRect(670, 240, 60, 60))
        self.pushButton_96 = QPushButton(self.centralwidget)
        self.pushButton_96.setObjectName(u"pushButton_96")
        self.pushButton_96.setGeometry(QRect(730, 240, 171, 60))
        self.pushButton_97 = QPushButton(self.centralwidget)
        self.pushButton_97.setObjectName(u"pushButton_97")
        self.pushButton_97.setGeometry(QRect(90, 300, 81, 60))
        self.pushButton_98 = QPushButton(self.centralwidget)
        self.pushButton_98.setObjectName(u"pushButton_98")
        self.pushButton_98.setGeometry(QRect(170, 300, 71, 60))
        self.pushButton_99 = QPushButton(self.centralwidget)
        self.pushButton_99.setObjectName(u"pushButton_99")
        self.pushButton_99.setGeometry(QRect(240, 300, 341, 60))
        self.pushButton_100 = QPushButton(self.centralwidget)
        self.pushButton_100.setObjectName(u"pushButton_100")
        self.pushButton_100.setGeometry(QRect(580, 300, 71, 60))
        self.pushButton_101 = QPushButton(self.centralwidget)
        self.pushButton_101.setObjectName(u"pushButton_101")
        self.pushButton_101.setGeometry(QRect(650, 300, 81, 60))
        self.pushButton_73 = QPushButton(self.centralwidget)
        self.pushButton_73.setObjectName(u"pushButton_73")
        self.pushButton_73.setGeometry(QRect(730, 300, 91, 60))
        self.pushButton_102 = QPushButton(self.centralwidget)
        self.pushButton_102.setObjectName(u"pushButton_102")
        self.pushButton_102.setGeometry(QRect(820, 120, 81, 121))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Esc", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"\u0451", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"Backspace", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"Tab", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"\u0439", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"\u0446", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"\u0443", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"\u043a", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"\u0435", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"\u043d", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"\u0433", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"\u0448", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"\u0449", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u"\u0437", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"\u0445", None))
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"\u044a", None))
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"F1", None))
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"F2", None))
        self.pushButton_31.setText(QCoreApplication.translate("MainWindow", u"F3", None))
        self.pushButton_32.setText(QCoreApplication.translate("MainWindow", u"F4", None))
        self.pushButton_33.setText(QCoreApplication.translate("MainWindow", u"F5", None))
        self.pushButton_34.setText(QCoreApplication.translate("MainWindow", u"F6", None))
        self.pushButton_35.setText(QCoreApplication.translate("MainWindow", u"F7", None))
        self.pushButton_36.setText(QCoreApplication.translate("MainWindow", u"F8", None))
        self.pushButton_38.setText(QCoreApplication.translate("MainWindow", u"F9", None))
        self.pushButton_39.setText(QCoreApplication.translate("MainWindow", u"F10", None))
        self.pushButton_40.setText(QCoreApplication.translate("MainWindow", u"F11", None))
        self.pushButton_41.setText(QCoreApplication.translate("MainWindow", u"F12", None))
        self.pushButton_37.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.pushButton_42.setText(QCoreApplication.translate("MainWindow", u"End", None))
        self.pushButton_43.setText(QCoreApplication.translate("MainWindow", u"Page Up", None))
        self.pushButton_44.setText(QCoreApplication.translate("MainWindow", u"Home", None))
        self.pushButton_45.setText(QCoreApplication.translate("MainWindow", u"Page Down", None))
        self.pushButton_46.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0435\u043b\u043a\u0430 \u0432\u0432\u0435\u0440\u0445", None))
        self.pushButton_48.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0435\u043b\u043a\u0430 \u0432\u043d\u0438\u0437", None))
        self.pushButton_49.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0435\u043b\u043a\u0430 \u0432\u043f\u0440\u0430\u0432\u043e", None))
        self.pushButton_50.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0435\u043b\u043a\u0430 \u0432\u043b\u0435\u0432\u043e", None))
        self.pushButton_51.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.pushButton_52.setText(QCoreApplication.translate("MainWindow", u"Insert", None))
        self.pushButton_53.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.pushButton_54.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_55.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton_56.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.pushButton_57.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.pushButton_58.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton_59.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton_60.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton_61.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_62.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButton_63.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton_64.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.pushButton_65.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
        self.pushButton_66.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_67.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_68.setText(QCoreApplication.translate("MainWindow", u"Print Screen", None))
        self.pushButton_69.setText(QCoreApplication.translate("MainWindow", u"Scroll Lock", None))
        self.pushButton_70.setText(QCoreApplication.translate("MainWindow", u"Caps Lock", None))
        self.pushButton_71.setText(QCoreApplication.translate("MainWindow", u"Shift", None))
        self.pushButton_72.setText(QCoreApplication.translate("MainWindow", u"Ctrl", None))
        self.pushButton_74.setText(QCoreApplication.translate("MainWindow", u"\u0444", None))
        self.pushButton_75.setText(QCoreApplication.translate("MainWindow", u"\u044b", None))
        self.pushButton_76.setText(QCoreApplication.translate("MainWindow", u"\u0432", None))
        self.pushButton_77.setText(QCoreApplication.translate("MainWindow", u"\u0430", None))
        self.pushButton_78.setText(QCoreApplication.translate("MainWindow", u"\u043f", None))
        self.pushButton_79.setText(QCoreApplication.translate("MainWindow", u"\u0440", None))
        self.pushButton_80.setText(QCoreApplication.translate("MainWindow", u"\u043e", None))
        self.pushButton_81.setText(QCoreApplication.translate("MainWindow", u"\u043b", None))
        self.pushButton_82.setText(QCoreApplication.translate("MainWindow", u"\u0434", None))
        self.pushButton_83.setText(QCoreApplication.translate("MainWindow", u"\u0436", None))
        self.pushButton_84.setText(QCoreApplication.translate("MainWindow", u"\u044d", None))
        self.pushButton_85.setText(QCoreApplication.translate("MainWindow", u"\\", None))
        self.pushButton_86.setText(QCoreApplication.translate("MainWindow", u"\u044f", None))
        self.pushButton_87.setText(QCoreApplication.translate("MainWindow", u"\u0447", None))
        self.pushButton_88.setText(QCoreApplication.translate("MainWindow", u"\u0441", None))
        self.pushButton_89.setText(QCoreApplication.translate("MainWindow", u"\u043c", None))
        self.pushButton_90.setText(QCoreApplication.translate("MainWindow", u"\u0438", None))
        self.pushButton_91.setText(QCoreApplication.translate("MainWindow", u"\u0442", None))
        self.pushButton_92.setText(QCoreApplication.translate("MainWindow", u"\u044c", None))
        self.pushButton_93.setText(QCoreApplication.translate("MainWindow", u"\u0431", None))
        self.pushButton_94.setText(QCoreApplication.translate("MainWindow", u"\u044e", None))
        self.pushButton_95.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.pushButton_96.setText(QCoreApplication.translate("MainWindow", u"Shift", None))
        self.pushButton_97.setText(QCoreApplication.translate("MainWindow", u"Win", None))
        self.pushButton_98.setText(QCoreApplication.translate("MainWindow", u"Alt", None))
        self.pushButton_99.setText(QCoreApplication.translate("MainWindow", u"Space", None))
        self.pushButton_100.setText(QCoreApplication.translate("MainWindow", u"Alt", None))
        self.pushButton_101.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u043e\u0435 \u043c\u0435\u043d\u044e", None))
        self.pushButton_73.setText(QCoreApplication.translate("MainWindow", u"Ctrl", None))
        self.pushButton_102.setText(QCoreApplication.translate("MainWindow", u"Enter", None))
    # retranslateUi

